export const ERROR_CODES = {
  VALIDATION_FAILED: "VALIDATION_FAILED",
  INVALID_PHONE: "INVALID_PHONE",
  INVALID_AMOUNT: "INVALID_AMOUNT",
  AMOUNT_TOO_LOW: "AMOUNT_TOO_LOW",
  MISSING_REQUIRED_FIELD: "MISSING_REQUIRED_FIELD",

  LOGIN_REQUIRED: "LOGIN_REQUIRED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  INVALID_PIN: "INVALID_PIN",
  TOO_MANY_ATTEMPTS: "TOO_MANY_ATTEMPTS",

  PERMISSION_DENIED: "PERMISSION_DENIED",
  ADMIN_PERMISSION_DENIED: "ADMIN_PERMISSION_DENIED",
  SUPER_ADMIN_REQUIRED: "SUPER_ADMIN_REQUIRED",

  MEMBER_NOT_FOUND: "MEMBER_NOT_FOUND",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  RECEIPT_NOT_FOUND: "RECEIPT_NOT_FOUND",
  ADMIN_NOT_FOUND: "ADMIN_NOT_FOUND",
  ADMIN_ALREADY_EXISTS: "ADMIN_ALREADY_EXISTS",
  ADMIN_GUARD_VIOLATION: "ADMIN_GUARD_VIOLATION",

  DUPLICATE_PHONE: "DUPLICATE_PHONE",
  DUPLICATE_MEMBER_CODE: "DUPLICATE_MEMBER_CODE",
  PAYMENT_ALREADY_VERIFIED: "PAYMENT_ALREADY_VERIFIED",
  INVALID_PAYMENT_STATUS_TRANSITION: "INVALID_PAYMENT_STATUS_TRANSITION",

  INVALID_RECEIPT_TOKEN: "INVALID_RECEIPT_TOKEN",
  RECEIPT_TOKEN_EXPIRED: "RECEIPT_TOKEN_EXPIRED",

  STORAGE_UPLOAD_FAILED: "STORAGE_UPLOAD_FAILED",
  UPLOAD_TOO_LARGE: "UPLOAD_TOO_LARGE",
  UNSUPPORTED_FILE_TYPE: "UNSUPPORTED_FILE_TYPE",

  INTERNAL_ERROR: "INTERNAL_ERROR",
  DATABASE_ERROR: "DATABASE_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
