export const SESSION_COOKIE_NAME = "ssf_session";
export const SESSION_COOKIE_MAX_AGE_SECONDS = 400 * 24 * 60 * 60;
export const SESSION_LIFETIME_MS = SESSION_COOKIE_MAX_AGE_SECONDS * 1000;
export const SESSION_REFRESH_INTERVAL_MS = 30 * 24 * 60 * 60 * 1000;
