"use client";

import React, { Suspense } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { PremiumReceiptCard } from "@/components/receipt/PremiumReceiptCard";
import { requestBackend } from "@/lib/api/backendClient";
import type { PaymentDTO } from "@/lib/backend/dto/payment.dto";

import Image from 'next/image';

function SuccessPageContent() {
  const searchParams = useSearchParams();
  const source = searchParams.get("source");
  const paymentId = searchParams.get("paymentId") || searchParams.get("order_id");
  const [payment, setPayment] = React.useState<PaymentDTO | null>(null);
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    if (!paymentId) { setError("Payment record is missing."); return; }
    
    const fetchReceipt = () => {
      requestBackend<PaymentDTO>(`/api/v1/payments/${encodeURIComponent(paymentId)}/receipt`)
        .then(setPayment)
        .catch((reason) => setError(reason instanceof Error ? reason.message : "Receipt not found."));
    };

    if (searchParams.has("order_id")) {
      requestBackend<PaymentDTO>("/api/v1/payments/cashfree/verify", {
        method: "POST",
        body: JSON.stringify({ cfOrderId: paymentId }),
      })
      .then(() => fetchReceipt())
      .catch((err) => {
         const msg = err instanceof Error ? err.message : "Verification failed";
         if (msg.includes("not successful yet")) {
           setError("Your payment is still being processed by the bank. Please check your dashboard in a few minutes.");
         } else {
           setError(msg);
         }
      });
    } else {
      fetchReceipt();
    }
  }, [paymentId, searchParams]);


  return (
    <main className="min-h-screen bg-gradient-to-b from-[#E6F0FA] to-[#F6F8FC] px-3 py-4 sm:px-6 sm:py-10 flex flex-col justify-between">
      <div className="mx-auto w-full max-w-[620px] flex-1 flex flex-col justify-center">
        
        {/* Branding Header with Floating Back Button */}
        <div className="relative mb-6 sm:mb-8 flex flex-col items-center justify-center">
          <Link
            href={source === "member" ? "/member/dashboard" : "/"}
            className="absolute left-0 top-0 p-2.5 sm:p-3 text-slate-500 hover:text-slate-900 hover:bg-white/60 rounded-full transition-colors print:hidden shadow-sm backdrop-blur-sm border border-slate-200/50"
            title="Go Back"
          >
            <ArrowLeft className="size-5" />
          </Link>
          
          <div className="flex flex-col items-center justify-center gap-2 mt-4 sm:mt-2 animate-in slide-in-from-top-4 fade-in duration-500">
            <Image 
              src="/logo/logo-transparent.svg" 
              alt="SSF Logo" 
              width={64} 
              height={64} 
              className="object-contain w-16 h-16 md:w-[88px] md:h-[88px] mix-blend-multiply"
              priority
            />
            <h1 className="text-xl md:text-3xl font-cooper text-[#063b78] tracking-tight text-center mt-1">
              SSF Alparamba Unit
            </h1>
          </div>
        </div>

        <div className="animate-in fade-in zoom-in-95 duration-500 delay-150 fill-mode-both">
          {error ? <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-center text-sm text-red-700">{error}</div> : payment ? <PremiumReceiptCard
            receiptId={payment.receiptId}
            method={payment.method}
            admin={payment.collectedByAdminName || "SSF Alparamba Unit"}
            payerName={payment.payerName}
            phone={payment.payerPhone}
            amount={payment.amount}
            category={payment.category}
            paidAt={payment.paidAt || payment.recordedAt}
          /> : <div className="rounded-2xl border border-slate-200 bg-white p-6 text-center text-sm text-slate-500">Loading receipt…</div>}
        </div>

      </div>
      
      {/* Footer placed at the bottom */}
      <div className="mt-8 mb-2">
        <p className="text-center text-[11px] sm:text-xs font-semibold text-slate-400">
          This receipt is computer generated by SSF Alparamba Unit.
        </p>
      </div>
    </main>
  );
}

export default function SuccessPage() {
  return (
    <Suspense
      fallback={
        <div className="flex min-h-screen flex-col items-center justify-center bg-[#F6F8FC] p-4">
          <div className="size-8 animate-spin rounded-full border-b-2 border-[#2563EB]" />
          <p className="mt-4 text-sm font-medium text-slate-500">Loading payment receipt...</p>
        </div>
      }
    >
      <SuccessPageContent />
    </Suspense>
  );
}
