"use client";

import React, { Suspense } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { PremiumReceiptCard } from "@/components/receipt/PremiumReceiptCard";
import { requestBackend } from "@/lib/api/backendClient";
import type { PaymentDTO } from "@/lib/backend/dto/payment.dto";

import Image from 'next/image';

function ReceiptPageContent({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = React.use(params);
  const searchParams = useSearchParams();
  const source = searchParams.get("source");
  const [payment, setPayment] = React.useState<PaymentDTO | null>(null);
  const [error, setError] = React.useState<string | null>(null);

  React.useEffect(() => {
    requestBackend<PaymentDTO>(`/api/v1/payments/${encodeURIComponent(resolvedParams.id)}/receipt`)
      .then(setPayment)
      .catch((reason) => setError(reason instanceof Error ? reason.message : "Receipt not found."));
  }, [resolvedParams.id]);



  return (
    <main className="min-h-[100svh] overflow-x-hidden relative bg-[#F6F8FC] dark:bg-slate-950 px-4 pb-5 pt-4 sm:px-6 sm:py-10 flex flex-col transition-colors duration-500 print:bg-white print:p-0 print:min-h-0 print:items-center print:justify-start">
      
      {/* Light Mode Original Background */}
      <div className="absolute inset-0 bg-gradient-to-b from-[#E6F0FA] to-[#F6F8FC] dark:hidden -z-20 print:hidden" />

      {/* Dark Mode Glowing Orbs (for the blur effect to be visible) */}
      <div className="absolute inset-0 hidden dark:block -z-20 overflow-hidden pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[60vw] h-[60vw] max-w-[500px] max-h-[500px] rounded-full bg-blue-600/20 mix-blend-screen blur-[80px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[60vw] h-[60vw] max-w-[500px] max-h-[500px] rounded-full bg-indigo-600/20 mix-blend-screen blur-[80px]" />
      </div>

      {/* Glassmorphism layer */}
      <div className="absolute inset-0 hidden dark:block backdrop-blur-3xl bg-slate-950/60 -z-10 transition-colors duration-500 print:hidden" />
      
      <div className="mx-auto w-full max-w-[430px] sm:max-w-[620px] flex-1 flex flex-col justify-start sm:justify-center z-10">
        
        {/* Branding Header with Floating Back Button */}
        <div className="relative mb-4 sm:mb-8 flex flex-col items-center justify-center print:hidden">
          <Link
            href={source === "member" ? "/member/dashboard" : "/"}
            className="absolute left-0 top-2 p-2.5 sm:p-3 text-slate-500 hover:text-slate-900 hover:bg-white/80 dark:hover:bg-slate-800/80 dark:text-slate-400 dark:hover:text-slate-100 rounded-full transition-colors print:hidden shadow-sm backdrop-blur-md border border-slate-200/50 dark:border-slate-700/50 bg-white/40 dark:bg-slate-900/40"
            title="Go Back"
          >
            <ArrowLeft className="size-5" />
          </Link>
          
          <div className="flex flex-col items-center justify-center gap-2 mt-4 sm:mt-2 animate-in slide-in-from-top-4 fade-in duration-500">
            <Image 
              src="/logo/atiyya-logo-icon.png" 
              alt="Atiyya Logo" 
              width={64} 
              height={64} 
              className="object-contain w-16 h-16 md:w-[88px] md:h-[88px]"
              priority
            />
            <h1 className="text-xl md:text-3xl font-cooper text-[#063b78] dark:text-slate-50 tracking-tight text-center mt-1 transition-colors duration-500">
              Atiyya Group
            </h1>
          </div>
        </div>

        <div className="animate-in fade-in zoom-in-95 duration-500 delay-150 fill-mode-both">
          {error ? <div className="rounded-2xl border border-red-200 bg-red-50 p-6 text-center text-sm text-red-700">{error}</div> : payment ? <PremiumReceiptCard
            receiptId={payment.receiptId}
            method={payment.method}
            admin={payment.collectedByAdminName || "Atiyya Group"}
            payerName={payment.payerName}
            phone={payment.payerPhone}
            amount={payment.amount}
            category={payment.category}
            paidAt={payment.paidAt || payment.recordedAt}
          /> : <div className="rounded-2xl border border-slate-200 bg-white p-6 text-center text-sm text-slate-500">Loading receipt…</div>}
        </div>

      </div>
      
      {/* Footer placed at the bottom */}
      <div className="mx-auto mt-5 w-full max-w-[430px] sm:max-w-[620px]">
        <p className="px-4 text-center text-[11px] sm:text-xs font-semibold leading-relaxed text-slate-400 print:hidden">
          This receipt is computer generated by Atiyya Group.
        </p>
      </div>
    </main>
  );
}

export default function ReceiptPage({ params }: { params: Promise<{ id: string }> }) {
  return (
    <Suspense
      fallback={
        <div className="flex min-h-screen flex-col items-center justify-center bg-[#F6F8FC] p-4">
          <div className="size-8 animate-spin rounded-full border-b-2 border-[#2563EB]" />
          <p className="mt-4 text-sm font-medium text-slate-500">Generating receipt...</p>
        </div>
      }
    >
      <ReceiptPageContent params={params} />
    </Suspense>
  );
}
