"use client";

import React, { Suspense } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { ArrowLeft } from "lucide-react";
import { PremiumReceiptCard } from "@/components/receipt/PremiumReceiptCard";

import confetti from 'canvas-confetti';
import Image from 'next/image';

function ReceiptPageContent({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = React.use(params);
  const searchParams = useSearchParams();

  const receiptId = resolvedParams.id || "TXN-8924719";
  const method = searchParams.get("method") || "upi";
  const admin = searchParams.get("admin") || "";
  const phone = searchParams.get("phone") || "Guest Member";
  const amount = searchParams.get("amount") || "100";
  const category = searchParams.get("category") || "dues";
  const source = searchParams.get("source");

  React.useEffect(() => {
    // Fire confetti on load without causing UI lag
    const duration = 3000;
    const end = Date.now() + duration;

    const interval: any = setInterval(() => {
      if (Date.now() > end) {
        return clearInterval(interval);
      }

      // Olive Green, Blue, White
      const customColors = ['#808000', '#2563EB', '#ffffff'];

      confetti({
        particleCount: 35,
        angle: 60,
        spread: 55,
        origin: { x: 0 },
        colors: customColors
      });
      confetti({
        particleCount: 35,
        angle: 120,
        spread: 55,
        origin: { x: 1 },
        colors: customColors
      });
    }, 250);
  }, []);

  return (
    <main className="min-h-[100svh] overflow-x-hidden bg-gradient-to-b from-[#E6F0FA] to-[#F6F8FC] px-4 pb-5 pt-4 sm:px-6 sm:py-10 flex flex-col">
      <div className="mx-auto w-full max-w-[430px] sm:max-w-[620px] flex-1 flex flex-col justify-start sm:justify-center">
        
        {/* Branding Header with Floating Back Button */}
        <div className="relative mb-4 sm:mb-8 flex flex-col items-center justify-center">
          <Link
            href={source === "member" ? "/member/dashboard" : "/"}
            className="absolute left-0 top-2 p-2.5 sm:p-3 text-slate-500 hover:text-slate-900 hover:bg-white/60 rounded-full transition-colors print:hidden shadow-sm backdrop-blur-sm border border-slate-200/50"
            title="Go Back"
          >
            <ArrowLeft className="size-5" />
          </Link>
          
          <div className="flex flex-col items-center justify-center gap-2 mt-4 sm:mt-2 animate-in slide-in-from-top-4 fade-in duration-500">
            <Image 
              src="/logo/logo-transparent.webp" 
              alt="SSF Logo" 
              width={64} 
              height={64} 
              className="object-contain w-16 h-16 md:w-[88px] md:h-[88px] mix-blend-multiply"
              priority
            />
            <h1 className="text-xl md:text-3xl font-cooper text-[#063b78] tracking-tight text-center mt-1">
              SSF Alparamba Unit
            </h1>
          </div>
        </div>

        <div className="animate-in fade-in zoom-in-95 duration-500 delay-150 fill-mode-both">
          <PremiumReceiptCard
            receiptId={receiptId}
            method={method}
            admin={admin}
            phone={phone}
            amount={amount}
            category={category}
          />
        </div>

      </div>
      
      {/* Footer placed at the bottom */}
      <div className="mx-auto mt-5 w-full max-w-[430px] sm:max-w-[620px]">
        <p className="px-4 text-center text-[11px] sm:text-xs font-semibold leading-relaxed text-slate-400 print:hidden">
          This receipt is computer generated by SSF Alparamba Unit.
        </p>
      </div>
    </main>
  );
}

export default function ReceiptPage({ params }: { params: Promise<{ id: string }> }) {
  return (
    <Suspense
      fallback={
        <div className="flex min-h-screen flex-col items-center justify-center bg-[#F6F8FC] p-4">
          <div className="size-8 animate-spin rounded-full border-b-2 border-[#2563EB]" />
          <p className="mt-4 text-sm font-medium text-slate-500">Generating receipt...</p>
        </div>
      }
    >
      <ReceiptPageContent params={params} />
    </Suspense>
  );
}
